export {
  FILTERED_PROJECTS_QUERY,
  PROJECT_BY_SLUG_QUERY,
  PROJECT_LIST_QUERY,
  PROJECT_SLUGS_QUERY,
} from './project'
export { FEATURED_PROJECTS_QUERY } from './featured'
export {
  CATEGORY_LIST_QUERY,
  DOOR_TYPE_LIST_QUERY,
  LOCATION_LIST_QUERY,
  WINDOW_STYLE_LIST_QUERY,
  WINDOW_TYPE_LIST_QUERY,
} from './taxonomy'
